In [1]:
l=[1,2,3]
l

[1, 2, 3]

In [2]:
import numpy as np

In [3]:
arr=np.array(l)
arr

array([1, 2, 3])

In [4]:
matrix=[[1,2,3],[4,5,6],[7,8,9]]
c=np.array(matrix)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
y=np.arange(0,11)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
y=np.arange(0,11,2)
y

array([ 0,  2,  4,  6,  8, 10])

In [8]:
z=np.zeros(3)
z

array([0., 0., 0.])

In [9]:
z=np.zeros((3,5))
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

To get 10 evenly spaced points from 0 to 5

In [12]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [13]:
#identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(5)

array([0.25636161, 0.41351322, 0.96807614, 0.73593931, 0.10897232])

In [17]:
np.random.rand(3,3)

array([[0.26868533, 0.76196431, 0.23025574],
       [0.17599706, 0.05841443, 0.34933548],
       [0.51867504, 0.18011191, 0.4138078 ]])

In [18]:
np.random.randint(1,100,10)   #1 is inclusive 100 is exclusive i.e not included

array([52, 57, 47, 40, 62, 47, 73, 38, 32, 67])

In [19]:
from numpy.random import randint
a=randint(0,10,25)
a

array([3, 3, 7, 6, 3, 3, 7, 0, 8, 7, 4, 4, 9, 3, 2, 7, 0, 8, 3, 4, 5, 5,
       9, 1, 5])

In [20]:
a.reshape(5,5)

array([[3, 3, 7, 6, 3],
       [3, 7, 0, 8, 7],
       [4, 4, 9, 3, 2],
       [7, 0, 8, 3, 4],
       [5, 5, 9, 1, 5]])

In [21]:
b=randint(0,10,5)
b

array([1, 7, 6, 0, 2])

In [22]:
b.max()

7

In [23]:
b.min()

0

In [24]:
b.argmax()

1

In [25]:
b.argmin()

3

In [27]:
b.dtype

dtype('int32')

In [29]:
b.shape

(5,)

In [35]:
arr1=np.arange(0,10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr1[0:4]=23
arr1

array([23, 23, 23, 23,  4,  5,  6,  7,  8,  9])

In [40]:
s=arr1[2:6]
s

array([23, 23,  4,  5])

In [41]:
s[:]=45
s

array([45, 45, 45, 45])

In [42]:
arr1

array([23, 23, 45, 45, 45, 45,  6,  7,  8,  9])

In [44]:
arr_2d=randint(0,30,25)
arr_2d=arr_2d.reshape(5,5)
arr_2d

array([[ 6, 14,  7,  8, 20],
       [ 9, 28,  0, 22, 22],
       [24,  7,  2, 13, 14],
       [22, 28, 22,  1, 12],
       [17, 10, 14, 18, 16]])

In [45]:
arr_2d[1][3]

22

In [46]:
arr_2d[1,3]


22

In [48]:
arr_2d[:3,2:]

array([[ 7,  8, 20],
       [ 0, 22, 22],
       [ 2, 13, 14]])

Conditional selection


In [50]:
array1=np.arange(0,11)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
b_arr= array1>5
b_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [56]:
array1[b_arr]


array([ 6,  7,  8,  9, 10])

In [57]:
q=array1[array1%2==0]
q


array([ 0,  2,  4,  6,  8, 10])

In [58]:
array1*10

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])